# Generated by Django 2.1.7 on 2019-03-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Потенциалы', 'verbose_name_plural': 'Потенциалы'},
        ),
        migrations.AlterModelOptions(
            name='contact1',
            options={'verbose_name': 'Клинент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
