# Generated by Django 2.1.7 on 2019-03-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.CharField(max_length=50, unique=True, verbose_name='Катигории квартир')),
            ],
            options={
                'verbose_name': 'Катигории квартир',
                'verbose_name_plural': 'Катигории квартир',
            },
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='сategories',
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Сategories',
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Bedrooms'),
            preserve_default=False,
        ),
    ]
