# Generated by Django 2.1.7 on 2019-03-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190326_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'МикроРайон', 'verbose_name_plural': 'МикроРайоны'},
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=50, unique=True, verbose_name='МикроРайон'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.City'),
        ),
    ]
