# Generated by Django 2.1.7 on 2019-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190326_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
    ]
