# Generated by Django 2.1.7 on 2019-03-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190326_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
