# Generated by Django 2.1.7 on 2019-03-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190327_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.District'),
        ),
    ]
