# Generated by Django 2.1.7 on 2019-03-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190328_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Bedrooms', verbose_name='Квартиры'),
        ),
    ]
