# Generated by Django 2.1.7 on 2019-03-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190328_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Bedrooms', verbose_name='Квартиры'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.District', verbose_name='МикроРайон'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.State', verbose_name='Район'),
        ),
    ]
