# Generated by Django 2.1.7 on 2019-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190329_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
