# Generated by Django 2.1.7 on 2019-03-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20190329_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='image',
        ),
    ]
