# Generated by Django 2.1.7 on 2019-03-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Риелтор', 'verbose_name_plural': 'Риелторы'},
        ),
    ]
